services:
  medipos-backend:
    build:
      context: .
      dockerfile: Presentation.API/Dockerfile
    container_name: medipos-backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8087:8080"

  medipos-frontend:
    build:
      context: ./Presentation.UI
      dockerfile: Dockerfile
    container_name: medipos-frontend
    restart: unless-stopped
    depends_on:
      - medipos-backend
    ports:
      - "8088:80"
